version: '3.9'

services:
  ecommerce_app:
    container_name: ecommerce_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src  # Syncs local source files for live updates
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm run dev








 